version: '3.8'

services:

  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: server
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app

  # Application Service
  app:
    container_name: app
    build: 
      context: .
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
